import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * One shared sidebar definition for every docs instance. Ordering comes from
 * the `sidebar_position` front matter and `_category_.json` files on disk, so
 * adding a page never requires touching this file.
 */
const sidebars: SidebarsConfig = {
  default: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
